#include <windows.h>
#include <commdlg.h>
#include <richedit.h>
#include <commctrl.h>
#include <stdio.h>
#include <wchar.h>
#include <stdbool.h>
#include <time.h>
#include <stdlib.h>
#include <locale.h>
#include "resource.h"

#define WM_CONSOLE_SET_STATUS (WM_USER + 1)

typedef struct {
    HWND hWnd;
        HWND hEdit;
            HWND hStatusBar;
                wchar_t statusText[256];
                } WindowData;

                WindowData window;
                bool consoleMode = false;

                void LogMessage(const wchar_t* format, ...) {
                    FILE* logFile = _wfopen(L"notepad.log", L"a");
                        if (!logFile) return;
                            time_t now;
                                time(&now);
                                    struct tm* tm_info = localtime(&now);
                                        wchar_t timeStr[20];
                                            wcsftime(timeStr, 20, L"%Y-%m-%d %H:%M:%S", tm_info);
                                                fwprintf(logFile, L"[%s] ", timeStr);
                                                    va_list args;
                                                        va_start(args, format);
                                                            vfwprintf(logFile, format, args);
                                                                va_end(args);
                                                                    fwprintf(logFile, L"\n");
                                                                        fclose(logFile);
                                                                            if (consoleMode) {
                                                                                    va_start(args, format);
                                                                                            vwprintf(format, args);
                                                                                                    va_end(args);
                                                                                                            wprintf(L"\n");
                                                                                                                }
                                                                                                                }

                                                                                                                void UpdateStatusBar(WindowData* wd) {
                                                                                                                    int parts[] = { 100, -1 };
                                                                                                                        SendMessageW(wd->hStatusBar, SB_SETPARTS, 2, (LPARAM)parts);
                                                                                                                            SendMessageW(wd->hStatusBar, SB_SETTEXTW, 1, (LPARAM)wd->statusText);
                                                                                                                            }

                                                                                                                            LRESULT CALLBACK WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) {
                                                                                                                                switch (msg) {
                                                                                                                                        case WM_CREATE: {
                                                                                                                                                    LoadLibraryW(L"riched32.dll");
                                                                                                                                                                window.hEdit = CreateWindowExW(WS_EX_CLIENTEDGE, L"RichEdit", L"",
                                                                                                                                                                                WS_CHILD | WS_VISIBLE | WS_VSCROLL | WS_HSCROLL | ES_MULTILINE | ES_AUTOVSCROLL | ES_AUTOHSCROLL | ES_NOHIDESEL,
                                                                                                                                                                                                0, 0, 100, 100, hWnd, (HMENU)101, GetModuleHandle(NULL), NULL);
                                                                                                                                                                                                            window.hStatusBar = CreateWindowExW(0, STATUSCLASSNAMEW, L"",
                                                                                                                                                                                                                            WS_CHILD | WS_VISIBLE | SBARS_SIZEGRIP,
                                                                                                                                                                                                                                            0, 0, 0, 0, hWnd, (HMENU)102, GetModuleHandle(NULL), NULL);
                                                                                                                                                                                                                                                        window.hWnd = hWnd;
                                                                                                                                                                                                                                                                    wcscpy(window.statusText, L"Ready");
                                                                                                                                                                                                                                                                                UpdateStatusBar(&window);
                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                            case WM_SIZE: {
                                                                                                                                                                                                                                                                                                                        RECT rcClient;
                                                                                                                                                                                                                                                                                                                                    GetClientRect(hWnd, &rcClient);
                                                                                                                                                                                                                                                                                                                                                int statusHeight = 20;
                                                                                                                                                                                                                                                                                                                                                            MoveWindow(window.hEdit, 0, 0, rcClient.right, rcClient.bottom - statusHeight, TRUE);
                                                                                                                                                                                                                                                                                                                                                                        MoveWindow(window.hStatusBar, 0, rcClient.bottom - statusHeight, rcClient.right, statusHeight, TRUE);
                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                    case WM_CONSOLE_SET_STATUS: {
                                                                                                                                                                                                                                                                                                                                                                                                                wchar_t* text = (wchar_t*)lParam;
                                                                                                                                                                                                                                                                                                                                                                                                                            wcsncpy(window.statusText, text, 255);
                                                                                                                                                                                                                                                                                                                                                                                                                                        window.statusText[255] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    UpdateStatusBar(&window);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                free(text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case WM_DESTROY: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        PostQuitMessage(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return DefWindowProcW(hWnd, msg, wParam, lParam);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        DWORD WINAPI ConsoleThread(LPVOID lpParam) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setlocale(LC_ALL, "");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                char cmd[1024];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while (1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("notepad> ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (fgets(cmd, sizeof(cmd), stdin) == NULL) break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cmd[strcspn(cmd, "\r\n")] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (strncmp(cmd, "notepad.status.set(", 18) == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                char text[256];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (sscanf(cmd, "notepad.status.set(%[^)])", text) == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            size_t len = mbstowcs(NULL, text, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            wchar_t* wtext = (wchar_t*)malloc((len + 1) * sizeof(wchar_t));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mbstowcs(wtext, text, len + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            PostMessageW(window.hWnd, WM_CONSOLE_SET_STATUS, 0, (LPARAM)wtext);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            INITCOMMONCONTROLSEX icex = { sizeof(INITCOMMONCONTROLSEX), ICC_BAR_CLASSES };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                InitCommonControlsEx(&icex);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int argc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        LPWSTR* argv = CommandLineToArgvW(GetCommandLineW(), &argc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 1; i < argc; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (wcscmp(argv[i], L"-ttle855") == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                consoleMode = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            AllocConsole();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _wfreopen(L"CONIN$", L"r", stdin);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _wfreopen(L"CONOUT$", L"w", stdout);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _wfreopen(L"CONOUT$", L"w", stderr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CreateThread(NULL, 0, ConsoleThread, NULL, 0, NULL);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            LocalFree(argv);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WNDCLASSW wc = {0};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    wc.lpfnWndProc = WndProc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        wc.hInstance = hInstance;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            wc.hIcon = LoadIconW(hInstance, MAKEINTRESOURCE(IDI_ICON1));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                wc.hCursor = LoadCursorW(NULL, IDC_ARROW);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    wc.hbrBackground = (HBRUSH)(COLOR_WINDOW+1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        wc.lpszClassName = L"MyNotepad";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            RegisterClassW(&wc);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                HWND hWnd = CreateWindowExW(WS_EX_CLIENTEDGE, L"MyNotepad", L"Notepad", WS_OVERLAPPEDWINDOW,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CW_USEDEFAULT, CW_USEDEFAULT, 640, 480, NULL, NULL, hInstance, NULL);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!hWnd) return 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ShowWindow(hWnd, nCmdShow);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    UpdateWindow(hWnd);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        MSG msg;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while (GetMessageW(&msg, NULL, 0, 0)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TranslateMessage(&msg);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            DispatchMessageW(&msg);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (consoleMode) FreeConsole();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        